# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RIBsSample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'RIBs', '~> 0.9'
  pod 'RxCocoa'
  # Pods for RIBsSample

end
